FROM node:24-bookworm-slim

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .

ARG BACKEND_URL=http://192.168.1.161:3002/api/v1
ENV BACKEND_URL=$BACKEND_URL
# NEXT_PUBLIC_* must be provided as Docker build args: Next.js embeds them
# into browser bundles during `npm run build`, not at container startup.
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_PAYMENTS_MODE
ARG NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_PAYMENTS_MODE=$NEXT_PUBLIC_PAYMENTS_MODE
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
ENV SESSION_COOKIE_SECURE=true
RUN npm run build

ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "run", "start", "--", "-p", "3000"]
